FROM nvidia/cuda:11.7.1-base-ubuntu22.04
RUN apt-get update && apt-get install -y \
    python3 \
    python3-pip \
    python3-dev \
    build-essential \
    libssl-dev \
    libffi-dev \
    python3-setuptools \
    python3-venv \
    git \
    && rm -rf /var/lib/apt/lists/* \
    && echo  "Download the model for ChatGLM2" \
    && git clone https://github.com/THUDM/ChatGLM2-6B \    
    && cd ChatGLM2-6B
